# Generated by Django 2.1.5 on 2021-04-30 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='core',
            name='postimage',
            field=models.ImageField(null=True, upload_to='postimage/'),
        ),
    ]
