# Generated by Django 2.1.5 on 2021-04-30 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_core_postimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='core',
            name='postimage',
            field=models.ImageField(blank=True, null=True, upload_to='postimage/'),
        ),
    ]
